### PR TITLE
Create namespace during upgrade with Helm >=v3

### LINKED ISSUE #32: Add --create-namespace flag
Since you already have the `--install` flag present I was wondering if there is anything blocking the support of `--create-namespace`? This will create the provided namespace when installing a new helm Chart in an ephemeral environment. Should I provide a PR for that?

### PR DESCRIPTION
**Pull request by riker09**
Closes #32

### CODE REVIEW

**Comment by yp28** [comment]
Any reason why this one isn't merged yet?

**Comment by riker09** [comment]
Maintainers don't maintain.

**Comment by colinjfw** [comment]
Sorry team, I will try and take a look this weekend.

**Comment by anthares101** [comment]
Any news about this?

**Comment by ykizin** [comment]
Hello! Any updates?

**Pull request closed without merging**
