### PR TITLE
Upgrade helm

### PR DESCRIPTION
**Pull request by mrahul17**

### CODE REVIEW

**Review by carlosstrand — APPROVED** [review]
Yeah! This change is important since we are facing this issue: #49

**Review by JeroenBoesten — APPROVED** [review]

**Comment by light94** [comment]
Hi @carlosstrand  and @JeroenBoesten thanks for approving this! Can you please verify if it is working for you so that i can finalize the changes?

**Comment by JeroenBoesten** [comment]
I can confirm that it solves the issue from #49

**Comment by diogopms** [comment]
Hey team, can we merge this PR? (I need that fix to deploy a new version of my code to production) Thanks 🙏🏻  😢

**Comment by light94** [comment]
@diogopms I am currently using a forked version of this repo with the above changes, given that it is taking time to merge this pr, I would recommend you to do the same

**Comment by glend-op** [comment]
This action is unusable unless this PR is merged.

**Pull request merged**
