### PR TITLE
Add input params

### PR DESCRIPTION
**Pull request by riker09**
Please note: I didn't add the `remove_canary` input parameter to the `action.yml` because it was not documented in the README.md.

### CODE REVIEW

**Comment by colinjfw** [comment]
I think after I merged the other CR's seeing a conflict now, I was going to resolve but I wasn't quite sure which parameters were being kept as required.

**Comment by riker09** [comment]
Sorry, I totally forgot about this PR. Should be all good now. But I'll keep on working on this GitHub action.

**Comment by assaf-grth** [comment]
Is there a due to this PR to be merged?

**Comment by romnn** [comment]
Would be great to fix this, since the warnings in the github actions log are very frustrating, making me wonder if I had the most recent version as described in the README.

This PR changes the inputs to `chart-version` from `chart_version`, which if fine and more consistent. Also, `index.js` replaces the _ with - so reading the values would totally work and really avoid frustration.

If I can do anything to help let me know!

**Comment by DenisDuev** [comment]
@riker09 can you also add `repository` in the `action.yaml`, it is already added in the index.js

**Pull request closed without merging**
